CREATE DATABASE CRUD_CAPAS_CSHARP
GO

USE CRUD_CAPAS_CSHARP
GO

/* ------------------------------------------------------------ USERS ------------------------------------------------------------ */
CREATE TABLE EMPLEADOS (
	ID INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
	FOLIO AS ('FE' + RIGHT('00000000' + CONVERT(VARCHAR, ID), (8))),
	NOMBRE NVARCHAR(20) NOT NULL,
	APELLIDOS NVARCHAR(32) NOT NULL,
	SEXO NVARCHAR(20) NOT NULL,
	FECHA_NACIMIENTO DATE NOT NULL,
	PUESTO NVARCHAR(32) NOT NULL,
	SUELDO DECIMAL(10,2) NOT NULL,
)
GO

INSERT INTO EMPLEADOS (NOMBRE, APELLIDOS, SEXO, FECHA_NACIMIENTO, PUESTO, SUELDO) VALUES ('Alejandro', 'Hernandez Soto', 'Masculino', '1993-05-08', 'Contador', 12500.98)
GO
INSERT INTO EMPLEADOS (NOMBRE, APELLIDOS, SEXO, FECHA_NACIMIENTO, PUESTO, SUELDO) VALUES ('Fernando', 'Garcia Ruiz', 'Masculino', '1980-02-10', 'Jefe de operaciones', 23500.00)
GO
INSERT INTO EMPLEADOS (NOMBRE, APELLIDOS, SEXO, FECHA_NACIMIENTO, PUESTO, SUELDO) VALUES ('Maria', 'Cruz Cruz', 'Femenino', '1996-10-12', 'Recepcionista', 9500.50)
GO

SELECT * FROM EMPLEADOS
GO

CREATE PROCEDURE SP_EMPLEADOS_BUSCAR
@BUSCAR NVARCHAR(32)
AS
SELECT * FROM EMPLEADOS WHERE NOMBRE LIKE '%' + @BUSCAR + '%' OR FOLIO LIKE '%' + @BUSCAR
GO

CREATE PROCEDURE SP_EMPLEADOS_INSERTAR
@NOMBRE NVARCHAR(20),
@APELLIDOS NVARCHAR(32),
@SEXO NVARCHAR(20),
@FECHA_NACIMIENTO DATE,
@PUESTO NVARCHAR(32),
@SUELDO DECIMAL(10,2)
AS
INSERT INTO EMPLEADOS(NOMBRE, APELLIDOS, SEXO, FECHA_NACIMIENTO, PUESTO, SUELDO) VALUES (@NOMBRE, @APELLIDOS, @SEXO, @FECHA_NACIMIENTO, @PUESTO, @SUELDO)
GO

CREATE PROCEDURE SP_EMPLEADOS_EDITAR
@ID INT,
@NOMBRE NVARCHAR(20),
@APELLIDOS NVARCHAR(32),
@SEXO NVARCHAR(20),
@FECHA_NACIMIENTO DATE,
@PUESTO NVARCHAR(32),
@SUELDO DECIMAL(10,2)
AS
UPDATE EMPLEADOS SET NOMBRE = @NOMBRE, APELLIDOS = @APELLIDOS, SEXO = @SEXO, FECHA_NACIMIENTO = @FECHA_NACIMIENTO, PUESTO = @PUESTO, SUELDO = @SUELDO
WHERE ID = @ID
GO

CREATE PROCEDURE SP_EMPLEADOS_ELIMINAR
@ID INT
AS
DELETE EMPLEADOS
WHERE ID = @ID
GO

CREATE PROCEDURE SP_USERS_VALIDATE
@USERNAME NVARCHAR(32),
@PASSWORD NVARCHAR(255)
AS
SELECT COUNT(*) FROM USERS WHERE USERNAME = @USERNAME AND PASSWORD = @PASSWORD
GO